export const EVENT_NAMES = {
  FILE_UPLOADED: 'File Uploaded',
  TRANSCRIBE_MEDIA: 'Media Transcription Submitted',
  TRANSLATE_MEDIA: 'Media Translation Submitted',
  REGENERATE_TRANSLATE_MEDIA: 'Media Translation Submitted',
  TRANSCRIBE_EDIT: 'Transcription Edited',
  TRANSLATE_EDIT: 'Translation Edited',
  DUB_MEDIA: 'Media Dubbing Submitted',
  REGENERATE_DUB_MEDIA: 'Media Dubbing Regenerated',
  SHARED_PROJECT: 'Shared project with user.',
  EXPORT_MEDIA: 'Media Exported',
  USER_LOGGED_IN: 'User Logged In',
  USER_LOGGED_OUT: 'User Logged Out',
  USER_SIGNED_UP: 'User Signed Up',
  SCREEN_RESOLUTION: 'User Screen Resolution',
  SEGMENT_EDIT: 'Segment Edit',
  CLICK: 'Click UI',
  VIDEO_SEEK: 'Video seek',
  VIDEO_SEEK_TIME: 'Video seektime wset'
};
